name: Deploy GithubPages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy to GITHUBPAGES
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.18.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:pages

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
